[relabel]

[autolabel."S-waiting-on-review"]
new_pr = true

[shortcut]

[rendered-link]
trigger-files = ["src/"]

[assign]
warn_non_default_branch = true

[assign.adhoc_groups]
fallback = [
    "@Mark-Simulacrum",
    "internal-sites",
]

[assign.owners]
"/blacksmith" = ["internal-sites"]
"/js" = ["internal-sites"]
"/src/community" = ["community"]
"/src/compiler" = ["compiler"]
"/src/crates-io" = ["crates-io"]
"/src/docs-rs" = ["docs-rs"]
"/src/editions" = ["edition"]
"/src/governance" = ["leadership-council"]
"/src/infra" = ["infra"]
"/src/lang" = ["lang"]
"/src/libs" = ["libs"]
"/src/platforms" = ["infra"]
"/src/release" = ["release"]
"/src/rustc-dev-guide" = ["rustc-dev-guide"]
"/src/rustdoc" = ["rustdoc"]
"/src/triagebot" = ["triagebot"]

[notify-zulip."I-libs-nominated"]
zulip_stream = 639962 # #t-libs/nominated
topic = "forge#{number}: {title}"
message_on_add = """\
[forge#{number} "{title}"](https://github.com/rust-lang/rust-forge/pull/{number}) has been nominated for discussion.
"""
message_on_remove = """\
forge#{number} is no longer nominated.
"""
